SHOW DATABASE;
CREATE DATABASE dbElectrodomesticos;
USE dbElectrodomesticos;
SELECT DATABASE(dbElectrodomesticos);

CREATE TABLE CLIENTE (
    CODCLI CHAR(4),
    NOMCLI VARCHAR(60),
    APECLI VARCHAR(80),
    EMACLI VARCHAR(80),
    CELCLI CHAR(9),
    DIRCLI VARCHAR(70),
    ESTCLI CHAR(1),
    CONSTRAINT CODCLI_PK PRIMARY KEY (CODCLI)
);

