SHOW DATABASE;
CREATE DATABASE dbElectrodomesticos;
USE dbelectrodomesticos;
SELECT DATABASE(dbelectrodomesticos);

CREATE TABLE CLIENTE (
    CODCLI CHAR(4),
    NOMCLI VARCHAR(60),
    APECLI VARCHAR(80),
    EMACLI VARCHAR(80),
    CELCLI CHAR(9),
    DIRCLI VARCHAR(70),
    ESTCLI CHAR(1),
    CONSTRAINT CODCLI_PK PRIMARY KEY (CODCLI)
);

CREATE TABLE VENDEDOR (
    CODVEND CHAR(4),
    NOMVEND VARCHAR(60),
    APEVEND VARCHAR(80),
    EMAVEND VARCHAR(80),
    CELVEND CHAR(9),
    DIRVEND VARCHAR(70),
    ESTVEND CHAR(1),
    CONSTRAINT CODVEND_PK PRIMARY KEY (CODVEND)
);

CREATE TABLE PRODUCTO(
    CODPRO CHAR(5),
    DESCPRO VARCHAR(80),
    CATPRO CHAR(1),
    PREPRO DECIMAL(8, 2),
    STOCKPRO INT,
    ESTPRO CHAR(1),
    CONSTRAINT CODPRO_PK PRIMARY KEY (CODPRO)
);

CREATE TABLE PROVEEDOR (
    CODPROV CHAR(5),
    RAZSOCPROV VARCHAR(90),
    RUCPROV VARCHAR(11),
    EMAPROV VARCHAR(70),
    ESTPROV CHAR(1),
    CONSTRAINT CODPROV_PK PRIMARY KEY (CODPROV)
);

CREATE TABLE VENTA (
    CODVEN CHAR(5),
    FECVEN DATETIME,
    CODCLI CHAR(4),
    CODVEND CHAR(4),
    ESTVEN CHAR(1),
    CONSTRAINT CODVEN_PK PRIMARY KEY (CODVEN)
);

CREATE TABLE VENTADETALLE (
    IDVENDET INT,
    CODVEN CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INT,
    CONSTRAINT IDVENDET_PK PRIMARY KEY (IDVENDET)
);

CREATE TABLE COMPRA (
    CODCOM CHAR(5),
    FECCOM DATETIME,
    CODVEND CHAR(4),
    CODPROV CHAR(5),
    ESTCOM CHAR(1);
    CONSTRAINT CODCON_PK PRIMARY KEY (CODCOM)
);

CREATE TABLE COMPRADETALLE (
    IDCOMDET INT,
    CODCOM CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INT,
    CONSTRAINT IDCOMDET_PK PRIMARY KEY (IDCOMDET)
);

ALTER TABLE VENDEDOR
    ADD CONSTRAINT CODVEND FOREIGN KEY (CODVEND) REFERENCES COMPRA (CODVEND);

ALTER TABLE VENDEDOR
    ADD CONSTRAINT CODVEND FOREIGN KEY (CODVEND) REFERENCES VENTA (CODVEND);

ALTER TABLE CLIENTE
    ADD CONSTRAINT CODCLI FOREIGN KEY (CODCLI) REFERENCES VENTA (CODCLI);

ALTER TABLE VENTA
    ADD CONSTRAINT CODVEN FOREIGN KEY (CODVEN) REFERENCES VENTADETALLE (CODVEN);

ALTER TABLE COMPRA
    ADD CONSTRAINT CODCOM FOREIGN KEY (CODCOM) REFERENCES COMPRADETALLE (CODCOM);

ALTER TABLE PROVEEDOR
    ADD CONSTRAINT CODPROV FOREIGN KEY (CODPROV) REFERENCES COMPRA (CODPROV);

ALTER TABLE PRODUCTO
    ADD CONSTRAINT CODPRO FOREIGN KEY (CODPRO) REFERENCES COMPRADETALLE (CODPRO);

ALTER TABLE PRODUCTO
    ADD CONSTRAINT CODPRO FOREIGN KEY (CODPRO) REFERENCES VENTADETALLE (CODPRO);